### ISSUE TITLE
Release 23.04 checklist

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#198]
For 23.04 let's try doing our validation async. Also replacing our usual spreadsheet for tasklists in an issue

## Verify pages

- Check page renders correctly
- Check for spelling/grammar problems
- Check that the instructions work as expected
- Ensure legacy pages with out of date instructions have a content warning
- If page needs updating convert the task to an issue and open a PR that closes the issue

```[tasklist]
### Tasks
- [x] https://docs.rapids.ai/deployment/nightly/
- [ ] https://github.com/rapidsai/deployment/issues/199
- [ ] https://github.com/rapidsai/deployment/issues/204
- [x] https://docs.rapids.ai/deployment/nightly/guides/scheduler-gpu-requirements.html
- [ ] https://docs.rapids.ai/deployment/nightly/guides/mig.html
- [x] https://docs.rapids.ai/deployment/nightly/guides/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-optuna-hpo/notebook.html
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.html
- [x] https://docs.rapids.ai/deployment/nightly/examples/
- [ ] https://github.com/rapidsai/deployment/issues/202
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-hpo/notebook.html
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-ec2-mnmg/notebook.html
- [x] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-higgs/notebook.html
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/aks.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azureml.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm-multi.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/
- [ ] https://github.com/rapidsai/deployment/issues/206
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/dataproc.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/vertex-ai.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/ibm/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/ibm/virtual-server.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ecs.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2-multi.html
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/eks.html
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/
- [ ] https://github.com/rapidsai/deployment/issues/200
- [x] https://docs.rapids.ai/deployment/nightly/local.html
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubernetes.html
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/databricks.html
- [x] https://docs.rapids.ai/deployment/nightly/platforms/
- [x] https://docs.rapids.ai/deployment/nightly/platforms/coiled.html
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubeflow.html
- [x] https://docs.rapids.ai/deployment/nightly/tools/rapids-docker.html
- [x] https://docs.rapids.ai/deployment/nightly/tools/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-kubernetes.html
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-helm-chart.html
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-operator.html
```

**Comment by jacobtomlinson** [comment]
Release 23.04 is complete
