### ISSUE TITLE
Consolidate dask-kubernetes client usage around kr8s

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#220]
> **Note**
> Creating in rapidsai/deployment so I can use tasklists. When tasklists are GA I'll migrate this issue to the dask/dask-kubernetes repo.

Today in `dask-kubernetes` we use `pykube-ng`, `dask_kubernetes.aiopykube`, `kubernetes_asyncio` and `subprocess`/`kubectl` to interact with the Kubernetes API. We do this because none of these libraries have all of the features needed in `dask-kubernetes` and so we end up stitching a bunch of them together. However, this is pretty unwieldy and hard to use.

I started [kr8s](https://kr8s.org) to extract all of the messy client code from `dask-kubernetes` (see https://github.com/dask/community/issues/313) and refractor it into something more simple, stable, well-scoped and reusable. The goal of that library is to find a balance between feature completeness, usability and simplicity.

Once `kr8s` is stable we should migrate all Kubernetes client usage to it and remove all of the other dependencies. 

## Scope

As we will be removing the classic `KubeCluster` and `HelmCluster` implementations in the future we should just focus on the operator's controller and `KubeCluster` implementation.

## Prerequisites

After a quick audit of dask-kubernetes here's a list of the features we use from the various client libraries. So the following features need to be completed, documented and generally stable in `kr8s` before we can switch.

```[tasklist]
# Prerequisites
- [x] Authenticate with service account, kubeconfig, exec, etc
- [x] Create Pods
- [x] Get Pod logs
- [x] List Pods
- [x] Delete Pods
- [x] Create service
- [x] Get service by name
- [x] Create custom resources
- [x] List custom resources
- [x] Get custom resource by name
- [x] Patch custom resources
- [x] Delete custom resource
- [ ] https://github.com/kr8s-org/kr8s/issues/27
- [ ] https://github.com/kr8s-org/kr8s/issues/28
- [ ] https://github.com/kr8s-org/kr8s/issues/39
```

## Related issues

The following issues will be resolved by migrating to `kr8s`

```[tasklist]
# Related issues
- [ ] https://github.com/dask/dask-kubernetes/issues/678
- [ ] https://github.com/dask/dask-kubernetes/issues/663
- [ ] https://github.com/dask/dask-kubernetes/issues/709
```

## Tasks

```[tasklist]
# Tasks
```

**Comment by jacobtomlinson** [comment]
As of https://github.com/dask/dask-kubernetes/pull/809 the operator controller KubeCluster are 100% `kr8s` 🎉
