### ISSUE TITLE
Retail forecasting blueprint

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#223]
Combine existing RAPIDS demos and documentation into an end-to-end demo showing some HPO with XGBoost on a typical retail forecasting problem.

Stack:
- Kubernetes for deployment and compute
- Kubeflow for Notebooks and experiment tracking
- RAPIDS (cudf) for preprocessing
- XGBoost for training
- Optuna for HPO
- Kserve for serving

Links:
- [Brief](https://docs.google.com/document/d/16g8da-AYBvmElY0rbgRpurOwlR5JMiU5sJYwx-ww1sI/edit#)
- [Kaggle Competition](https://www.kaggle.com/c/m5-forecasting-accuracy)
- [Kaggle Solutions (A1-A5)](https://github.com/Mcompetitions/M5-methods/tree/master/Code%20of%20Winning%20Methods)
- [Private repo with extended solutions](https://gitlab-master.nvidia.com/NVRetail/demand-prediction/m5-forecasting)

```[tasklist]
### Blog post outline
- [ ] Introduce the problem (retail forecasting from Kaggle)
- [ ] Link to Kubeflow/Kubernetes docs
- [ ] Link to a notebook to preprocess the data based on the winning solutions
- [ ] Link to a notebook to train model with XGBoost and Optuna based on the winning solutions
- [ ] Store the best model in GCS
- [ ] Serve the model with Kserve
```

```[tasklist]
### TODOs
- [ ] https://github.com/rapidsai/deployment/issues/225
- [ ] https://github.com/rapidsai/deployment/issues/224
- [ ] https://github.com/rapidsai/deployment/issues/251
- [x] Store model outputs in Kubeflow/GCS
- [ ] https://github.com/rapidsai/deployment/issues/285
- [ ] https://github.com/rapidsai/deployment/issues/286
```

**Comment by jayavenkatesh19** [comment]
https://developer.nvidia.com/blog/best-practices-of-using-ai-to-develop-the-most-accurate-retail-forecasting-solution/ This is the blog post already published

**Comment by ncclementi** [comment]
There is also this: https://docs.rapids.ai/deployment/stable/examples/time-series-forecasting-with-hpo/notebook/
