### ISSUE TITLE
Using Apache Beam with Dask has a scaling limit of 100-200 GPUs

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#235]
_This is a high-level tracker issue for issues/PRs in both Dask and Beam._

```[tasklist]
### Issues
- [ ] https://github.com/apache/beam/issues/26669
- [ ] https://github.com/dask/dask/issues/10291
```

```[tasklist]
### PRs
- [ ] https://github.com/dask/dask/pull/10294
```

## Summary

I'm exploring some unexpected behaviour which is creating a [limitation on how far Apache Beam workloads can scale](https://github.com/apache/beam/issues/26669) with a [Dask runner](https://beam.apache.org/releases/pydoc/2.44.0/apache_beam.runners.dask.dask_runner.html). This was originally discovered on NGC Base Command Platform, although the bug seems to be general to all Beam on Dask deployments.

Beam uses `dask.bag` to store collections of items (which Beam calls a PCollection). Calling `beam.Create(iterable)` is [translated to `dask.bag.from_sequence(iterable)`](https://github.com/apache/beam/blob/96989dc9b11457e5d03bb145877faa5f0869db23/sdks/python/apache_beam/runners/dask/transform_evaluator.py#L62). It then translates calls to functions like `beam.ParDo` to `dask.bag.map`.

The problem we are investigating was discovered when a Beam workload wouldn't scale beyond ~200 workers. Additional workers added to the Dask cluster would sit idle. After some investigation, it seems the root cause is [Dask Bag's default partitioning scheme](https://github.com/dask/dask/blob/11f2b83ee034aea7837691f9a0d4ede6309d6194/dask/bag/core.py#L1776-L1780) which limits you to 100 tasks beyond a certain number of items in the bag.

This means it is never possible to full utilize clusters with more than 200 GPUs.

![image](https://github.com/rapidsai/deployment/assets/1610850/dec9112a-f8be-4037-877a-f6ba7cf923f0)

**Comment by jacobtomlinson** [comment]
This has been fixed in Dask. There are further improvements that could be made to beam, but there seems to be little to no engagement from the beam community on this. So I'm going to close this out as completed and leave https://github.com/apache/beam/issues/26669 around in case beam folks want to collaborate and iterate further.
