### ISSUE TITLE
Release 23.06 checklist

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#236]
# Release checklist

For the upcoming release we need to verify our documentation. This is a best efforts activity
so please refer to the checklist from the previous release (#198) and focus on pages that were not
verified last time.

## Verify pages

- Look at the nightly build of each page listed below
- Check page renders correctly
- Check for spelling/grammar problems
- Check that the instructions work as expected
- Ensure legacy pages with out of date instructions have a content warning
- If page needs updating convert the task to an issue and open a PR that closes the issue

```[tasklist]
### Pages
- [x] https://docs.rapids.ai/deployment/nightly/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2-multi/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ecs/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/eks/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/aks/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/azureml/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm-multi/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/dataproc/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/gke/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/vertex-ai/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/ibm/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/ibm/virtual-server/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/
- [x] https://docs.rapids.ai/deployment/nightly/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-ec2-mnmg/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-optuna-hpo/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-higgs/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-hpo/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-randomforest-gpu-hpo-dask/notebook/
- [x] https://docs.rapids.ai/deployment/nightly/guides/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/azure/infiniband/
- [x] https://docs.rapids.ai/deployment/nightly/guides/l4-gcp/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/mig/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/scheduler-gpu-requirements/
- [x] https://docs.rapids.ai/deployment/nightly/hpc/
- [x] https://docs.rapids.ai/deployment/nightly/local/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/coiled/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/colab/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/databricks/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kserve/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubeflow/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubernetes/
- [x] https://docs.rapids.ai/deployment/nightly/tools/
- [x] https://docs.rapids.ai/deployment/nightly/tools/dask-cuda/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-helm-chart/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-kubernetes/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-operator/
- [x] https://docs.rapids.ai/deployment/nightly/tools/rapids-docker/
```

_Issue text generated by `scripts/gen_release_checklist_issue.sh`._
