### ISSUE TITLE
TCO Mapping / Benchmarking

### ISSUE THREAD

**Issue by skirui-source** [rapidsai/deployment#249]
```[tasklist]
### Tasks
- [x] https://github.com/rapidsai/deployment/issues/257
- [ ] https://github.com/rapidsai/deployment/issues/280
- [ ] https://github.com/rapidsai/deployment/issues/258
```

**Comment by skirui-source** [comment]
I created  a separate repo to track my work, which can found [here](https://github.com/skirui-source/tco_hpo_gpu_cpu_perf_benchmark/blob/main/code/hpo_gpu.py). Once complete, I will integrate into the rapids deployment repo
