### ISSUE TITLE
Release 23.12 checklist

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#302]
# Release checklist

For the upcoming release we need to verify our documentation. This is a best efforts activity
so please refer to the checklist from the previous release and focus on pages that were not
verified last time.

## Verify pages

- Look at the nightly build of each page listed below
- Check page renders correctly
- Check for spelling/grammar problems
- Check that the instructions work as expected
- Ensure legacy pages with out of date instructions have a content warning
- If page needs updating convert the task to an issue and open a PR that closes the issue

```[tasklist]
### Index/Non-technical
- [x] https://docs.rapids.ai/deployment/nightly/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/ibm/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/nvidia/
- [x] https://docs.rapids.ai/deployment/nightly/examples/
- [x] https://docs.rapids.ai/deployment/nightly/guides/
- [x] https://docs.rapids.ai/deployment/nightly/local/
- [x] https://docs.rapids.ai/deployment/nightly/platforms/
- [x] https://docs.rapids.ai/deployment/nightly/tools/
```

```[tasklist]
### P0
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azureml/
- [ ] https://github.com/rapidsai/deployment/issues/290
- [x] https://docs.rapids.ai/deployment/nightly/cloud/nvidia/bcp/
- [x] https://docs.rapids.ai/deployment/nightly/platforms/colab/
- [x] https://docs.rapids.ai/deployment/nightly/platforms/databricks/
```

```[tasklist]
### P1
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/eks/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/aks/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/gke/
```

```[tasklist]
### P2
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2-multi/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/ecs/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm-multi/
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/dataproc/
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/ibm/virtual-server/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/
- [x] https://docs.rapids.ai/deployment/nightly/examples/rapids-azureml-hpo/notebook/
- [x] https://docs.rapids.ai/deployment/nightly/examples/rapids-ec2-mnmg/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-optuna-hpo/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-higgs/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-hpo/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/time-series-forecasting-with-hpo/notebook/
- [x] https://docs.rapids.ai/deployment/nightly/examples/xgboost-azure-mnmg-daskcloudprovider/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-ngc/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-randomforest-gpu-hpo-dask/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-rf-gpu-cpu-benchmark/notebook/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/azure/infiniband/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/l4-gcp/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/mig/
- [ ] https://docs.rapids.ai/deployment/nightly/guides/scheduler-gpu-requirements/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/coiled/
- [ ] https://docs.rapids.ai/deployment/nightly/hpc/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kserve/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubeflow/
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubernetes/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/dask-cuda/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-helm-chart/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-kubernetes/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-operator/
- [ ] https://docs.rapids.ai/deployment/nightly/tools/rapids-docker/
```

_Issue text generated by `scripts/gen_release_checklist_issue.sh`._

**Comment by jacobtomlinson** [comment]
The 23.12 release is now complete.
