### ISSUE TITLE
RAPIDS + AI Workbench

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#320]
Test and document using RAPIDS with [NVIDIA AI Workbench](https://www.nvidia.com/en-gb/deep-learning-ai/solutions/data-science/workbench/).
```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/deployment/issues/321
- [x] Test a Local CPU -> Remote cudf.pandas workflow
- [ ] https://github.com/rapidsai/deployment/issues/341
- [ ] https://github.com/rapidsai/deployment/issues/342
- [x] Add Workbench labels to RAPIDS container
- [ ] https://github.com/rapidsai/deployment/issues/433
```
