### ISSUE TITLE
Release 24.10 Checklist

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#434]
# Release checklist

For the upcoming release we need to verify our documentation. This is a best efforts activity
so please refer to the checklist from the previous release and focus on pages that were not
verified last time.

## Verify pages

- Look at the nightly build of each page listed below
- Check page renders correctly
- Check for spelling/grammar problems
- Check that the instructions work as expected
- Ensure legacy pages with out of date instructions have a content warning
- If page needs updating convert the task to an issue and open a PR that closes the issue

### Index/Non-technical

- [x] https://docs.rapids.ai/deployment/nightly/
- [x] https://docs.rapids.ai/deployment/nightly/cloud
- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp
- [x] https://docs.rapids.ai/deployment/nightly/cloud/ibm
- [x] https://docs.rapids.ai/deployment/nightly/cloud/nvidia
- [x] https://docs.rapids.ai/deployment/nightly/developer
- [x] https://docs.rapids.ai/deployment/nightly/developer/ci
- [x] #437
- [x] https://docs.rapids.ai/deployment/nightly/guides
- [x] https://docs.rapids.ai/deployment/nightly/hpc
- [x] https://docs.rapids.ai/deployment/nightly/local
- [x] https://docs.rapids.ai/deployment/nightly/nims
- [x] https://docs.rapids.ai/deployment/nightly/platforms
- [x] https://docs.rapids.ai/deployment/nightly/tools

### P0

- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker (broken for 24.10: https://github.com/rapidsai/deployment/issues/443)
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azureml
- [x] #441
- [x] https://docs.rapids.ai/deployment/nightly/cloud/nvidia/bcp
- [x] https://docs.rapids.ai/deployment/nightly/platforms/colab (https://github.com/rapidsai/deployment/pull/451)
- [x] https://docs.rapids.ai/deployment/nightly/platforms/databricks

### P1

- [x] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2
- [x] #459
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/aks
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine
- [x] #447

### P2

- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2-multi (broken: https://github.com/rapidsai/deployment/issues/455)
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/aws/ecs
- [x] https://docs.rapids.ai/deployment/nightly/cloud/azure/azure-vm-multi
- [x] https://docs.rapids.ai/deployment/nightly/cloud/gcp/dataproc
- [ ] https://docs.rapids.ai/deployment/nightly/cloud/ibm/virtual-server
- [x] https://docs.rapids.ai/deployment/nightly/developer/ci/github-actions
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-1brc-single-node/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook
- [x] https://docs.rapids.ai/deployment/nightly/examples/rapids-azureml-hpo/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-ec2-mnmg/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-optuna-hpo/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-higgs/notebook (broken for 24.10: https://github.com/rapidsai/deployment/issues/443)
- [ ] https://docs.rapids.ai/deployment/nightly/examples/rapids-sagemaker-hpo/notebook (broken for 24.10: https://github.com/rapidsai/deployment/issues/443)
- [ ] https://docs.rapids.ai/deployment/nightly/examples/time-series-forecasting-with-hpo/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-azure-mnmg-daskcloudprovider/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-dask-databricks/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-job-parallel-ngc/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-gpu-hpo-mnmg-parallel-k8s/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-randomforest-gpu-hpo-dask/notebook
- [ ] https://docs.rapids.ai/deployment/nightly/examples/xgboost-rf-gpu-cpu-benchmark/notebook
- [x] https://docs.rapids.ai/deployment/nightly/guides/azure/infiniband
- [ ] https://docs.rapids.ai/deployment/nightly/guides/caching-docker-images
- [ ] https://docs.rapids.ai/deployment/nightly/guides/colocate-workers
- [x] https://docs.rapids.ai/deployment/nightly/guides/l4-gcp
- [ ] https://docs.rapids.ai/deployment/nightly/guides/mig
- [ ] https://docs.rapids.ai/deployment/nightly/guides/scheduler-gpu-optimization
- [ ] https://docs.rapids.ai/deployment/nightly/guides/scheduler-gpu-requirements
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/brev-dev
- [x] https://docs.rapids.ai/deployment/nightly/platforms/coiled
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kserve
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubeflow
- [ ] https://docs.rapids.ai/deployment/nightly/platforms/kubernetes
- [x] https://docs.rapids.ai/deployment/nightly/tools/dask-cuda
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-helm-chart
- [ ] https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-operator
- [x] https://docs.rapids.ai/deployment/nightly/tools/rapids-docker

_Issue text generated by scripts/gen_release_checklist_issue.py._

**Comment by jameslamb** [comment]
👋🏻 I'm going to start with all the AWS ones (working from P0 down)

**Comment by jameslamb** [comment]
> https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker

This one is broken for 24.10, because RAPIDS 24.10 can't be installed alongside the `sagemaker` library. Documented in #443.
